DROP TABLE clients;
DROP TABLE comptes;
DROP TABLE operations;

CREATE TABLE clients
(
	id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	nom VARCHAR(150),
	prenom VARCHAR(150),
	telephone VARCHAR(15)
)

CREATE TABLE operations
(
	id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	montant DECIMAL,
	date_operation DATETIME,
	compte_id INT
)

CREATE TABLE comptes
(
	id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	solde DECIMAL,
	client_id INT
)

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'comptes';
SELECT * FROM clients WHERE id = 1;